### ISSUE TITLE
Watch all namespaces by default

### ISSUE THREAD

**Issue by SimonBarendse** [1Password/connect-helm-charts#54]
### Summary
Don't override the setting in https://github.com/1Password/onepassword-operator/pull/40

### Use cases
I want to configure as little as possible and don't have to redeploy when I add more namespaces.

### Proposed solution
Set `OP_WATCH_NAMESPACES: []` in [`values.yml`](https://github.com/1Password/connect-helm-charts/blob/1022ff6e9f61d60713cccc6aa0ad15a7477aa441/charts/connect/values.yaml#L35)

### Is there a workaround to accomplish this today?
Override the `OP_WATCH_NAMESPACES` configured by the Helm chart.

### References & Prior Work
- https://github.com/1Password/onepassword-operator/pull/40
- https://github.com/1Password/onepassword-operator/issues/8

**Comment by SimonBarendse** [comment]
Figured this one out, we can use a `ClusterRoleBinding` in case we're watching all namespaces. Related: #55

**Comment by rchenzheng** [comment]
> Figured this one out, we can use a `ClusterRoleBinding` in case we're watching all namespaces. Related: #55

I opened a PR to accomplish this https://github.com/1Password/connect-helm-charts/pull/62

**Comment by insider89** [comment]
Can anyone review PR above? It's very important to have ability to watch all namespaces for our cases. Thx in advance.

**Comment by roderik** [comment]
Any idea when this is going to be released? 

We are using a gitops approach (via Pulumi) and I'm struggling with chicken/egg problems. To configure a shared operator per cluster to watch a namespace, it needs to exist. But the namespaces are env related and might not exist yet, when they are created, they do not deploy anything in them since they depend on secrets by the operator, that is not watching yet. Doing the runs by hand twice works, but for our purposes I had to move to connect+operator per namespace. This PR would solve this.

**Comment by SimonBarendse** [comment]
Thank you @rchenzheng for opening the PR! :blue_heart: I've left a review just now.

I appreciate you all sharing this is important for you. We don't usually make any promises on when we'll release new functionality, so we never create expectations we're not delivering on when we hit unexpected challenges or when other features we're adding for you take precedence. Thank you for your understanding.

**Comment by edif2008** [comment]
Hey.
Great news. We released 1.5.0, which includes the clusterrolebinding compatibility, as well as watching all namespaces by default.
